# CustomItems by goncalomb - goncalomb.com
name: CustomItemsAPI
main: com.goncalomb.bukkit.customitems.CustomItemsAPI
version: 0.0.3
author: goncalomb

permissions:
  customitemsapi.*:
    default: op
    children:
      customitemsapi.customitem: true