# CustomItems by goncalomb - goncalomb.com
name: CustomItems
main: com.goncalomb.bukkit.customitems.CustomItems
version: 0.0.2
author: goncalomb

permissions:
  customitems.*:
    default: op
    children:
      customitems.customitem: true