name: Java CI (Deploy)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Deploy with Maven
      run: mvn deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/goncalomb/NBTEditor -Dregistry=https://maven.pkg.github.com/goncalomb -Dtoken=${{ secrets.GITHUB_TOKEN }}
